import { describe, it, expect } from 'vitest';
import { stripTerraformMetadata, stripGitignoreMetadata } from '../src/commands/eject.js';

describe('eject metadata stripping', () => {
    it('strips grada headers and tag blocks', () => {
        const content = '# grada generated infrastructure\n'
            + 'provider "aws" {\n'
            + '  region = "us-east-2"\n\n'
            + '  default_tags {\n'
            + '    tags = {\n'
            + '      ManagedBy = "grada"\n'
            + '    }\n'
            + '  }\n'
            + '}\n';
        const cleaned = stripTerraformMetadata(content);
        expect(cleaned).not.toContain('grada generated infrastructure');
        expect(cleaned).not.toContain('ManagedBy');
        expect(cleaned).toContain('provider "aws"');
        expect(cleaned).toContain('region = "us-east-2"');
    });

    it('strips legacy deploy-stack headers, tag blocks, and lambda suffixes', () => {
        const content = '# deploy-stack generated infrastructure (Lambda target)\n'
            + 'provider "aws" {\n'
            + '  default_tags {\n'
            + '    tags = {\n'
            + '      ManagedBy = "deploy-stack"\n'
            + '    }\n'
            + '  }\n'
            + '}\n';
        const cleaned = stripTerraformMetadata(content);
        expect(cleaned).not.toContain('deploy-stack');
        expect(cleaned).not.toContain('Lambda target');
        expect(cleaned).toContain('provider "aws"');
    });

    it.each([
        ['grada', '# grada addon: storage:s3\n# Generated by `grada add storage:s3`. Do not edit by hand unless\n'],
        ['legacy', '# deploy-stack addon: storage:s3\n# Generated by `deploy-stack add storage:s3`. Do not edit by hand unless\n'],
    ])('strips %s addon headers but keeps billing docs', (_label, header) => {
        const content = `${header}# you know what you are doing — re-running with --force overwrites this file.\n`
            + '#\n# Billing: usage-billed.\n\nresource "aws_s3_bucket" "x" {}\n';
        const cleaned = stripTerraformMetadata(content);
        expect(cleaned).not.toContain('addon: storage:s3');
        expect(cleaned).not.toContain('Generated by');
        expect(cleaned).not.toContain('overwrites this file');
        expect(cleaned).toContain('# Billing: usage-billed.');
        expect(cleaned).toContain('resource "aws_s3_bucket" "x" {}');
    });

    it('strips both gitignore backup stanzas', () => {
        const content = 'node_modules/\n\n# grada backups\n*.bak.*\n\n# deploy-stack backups\n*.bak.*\n';
        const cleaned = stripGitignoreMetadata(content);
        expect(cleaned).not.toContain('backups');
        expect(cleaned).not.toContain('*.bak.*');
        expect(cleaned).toContain('node_modules/');
    });

    it('leaves domain markers and user content untouched', () => {
        const content = '# grada:domain-mode=route53\n# grada:zone-id=Z123\n'
            + '# A user comment about grada add workflows.\n';
        expect(stripTerraformMetadata(content)).toBe(content);
        expect(stripGitignoreMetadata('dist/\n')).toBe('dist/\n');
    });
});
