import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';
import { intro, outro, spinner, log, cancel } from '@clack/prompts';
import color from 'picocolors';
import { renderDryRunPreview, parseTerraformConfig } from '../utils/visualizer.js';
import { detectFramework } from '../utils/detector.js';

// Helper to run a command while piping the latest stdout line into a @clack spinner
function runTerraformCommand(args, cwd, spin, loadingPrefix) {
    return new Promise((resolve, reject) => {
        const child = spawn('terraform', args, { cwd });
        let errorOutput = '';
        let isDone = false;

        child.stdout.on('data', (data) => {
            if (isDone) return;
            const lines = data.toString().split('\n').filter(line => line.trim() !== '');
            if (lines.length > 0) {
                const latestLine = lines[lines.length - 1].trim();
                const display = latestLine.length > 120 ? latestLine.substring(0, 117) + '...' : latestLine;
                spin.message(`${loadingPrefix} - ${color.dim(display)}`);
            }
        });

        child.stderr.on('data', (data) => {
            errorOutput += data.toString();
        });

        child.on('close', (code) => {
            isDone = true;
            if (code === 0) {
                resolve();
            } else {
                reject(new Error(errorOutput || `Terraform exited with code ${code}`));
            }
        });

        child.on('error', (err) => {
            isDone = true;
            reject(err);
        });
    });
}

// Helper to pull JSON outputs from Terraform
function getTerraformOutputs(cwd) {
    return new Promise((resolve) => {
        const child = spawn('terraform', ['output', '-json'], { cwd });
        let outputData = '';

        child.stdout.on('data', (data) => {
            outputData += data.toString();
        });

        child.on('close', (code) => {
            if (code === 0) {
                try {
                    resolve(JSON.parse(outputData));
                } catch {
                    resolve({});
                }
            } else {
                resolve({});
            }
        });

        child.on('error', () => {
            resolve({});
        });
    });
}

export async function applyStack(options = {}) {
    intro(color.bgCyan(color.black(' deploy-stack apply ☁️  ')));

    const targetDir = process.cwd();
    const tfDir = path.join(targetDir, 'terraform');

    // 1. Verify that the user is inside a project generated by deploy-stack
    if (!fs.existsSync(tfDir) || !fs.existsSync(path.join(tfDir, 'main.tf'))) {
        log.error(color.red('✖ No terraform directory found in current path.'));
        log.message('Please run "npx deploy-stack" first to generate your infrastructure templates.');
        process.exit(1);
    }

    // 2. Read the actual AWS configuration from disk (CPU, Memory, Region, Database)
    const detectedConfig = parseTerraformConfig(tfDir);

    // 3. Detect the framework name using your existing detector
    const detectedFw = detectFramework(targetDir);
    detectedConfig.framework = detectedFw ? detectedFw.name : 'Container';

    // 4. Run the visualizer (passing the flag so it knows whether to prompt)
    if (options.isDryRun) {
        await renderDryRunPreview(detectedConfig, true);
        outro(color.green('Dry run complete. No infrastructure was provisioned.'));
        process.exit(0);
    } else {
        await renderDryRunPreview(detectedConfig, false);
    }

    const s = spinner();

    try {
        // 5. Run terraform init
        s.start('Initializing Terraform plugins...');
        await runTerraformCommand(['init', '-upgrade'], tfDir, s, 'Initializing');
        log.success('Terraform initialized.');

        // 6. Run terraform apply
        s.start('Provisioning AWS infrastructure (this may take 3–5 minutes)...');
        await runTerraformCommand(['apply', '-auto-approve'], tfDir, s, 'Provisioning');
        s.stop('Cloud resources provisioned.');

        // 7. Extract and print the outputs
        const outputs = await getTerraformOutputs(tfDir);

        const cfUrl = outputs.cloudfront_url?.value;
        const albUrl = outputs.alb_direct_url?.value;

        let finalMessage = color.green('✅ Infrastructure is live!');
        if (cfUrl) finalMessage += `\n  🌍 CDN: ${color.cyan(cfUrl)}`;
        if (albUrl) finalMessage += `\n  🚦 ALB: ${color.gray(albUrl)}`;

        outro(`${finalMessage}\n\n  ${color.yellow('Push code to deploy your app and clear the 503 error:')}\n  ${color.cyan('git add . && git commit -m "ci: infra" && git push origin main')}`);

        process.exit(0);

    } catch (error) {
        s.stop(color.red('❌ Terraform apply failed.'));

        const errString = error.message || "";

        if (errString.includes('EntityAlreadyExists') && errString.includes('token.actions.githubusercontent.com')) {
            log.error(color.red('GitHub OIDC Provider Conflict Detected'));
            log.message('AWS only allows one GitHub Actions provider per account, and you already have one configured.');
            log.message('');
            log.message(`${color.bold('How to fix this:')}`);
            log.message(`1. Open ${color.cyan('terraform/oidc.tf')}`);
            log.message(`2. Change ${color.green('create_oidc_provider = true')} to ${color.green('create_oidc_provider = false')}`);
            log.message(`3. Run ${color.cyan('npx deploy-stack apply')} again.`);
        } else {
            // Generic fallback for unknown errors
            log.error(color.red(errString));
            log.message(`${color.bold('To debug manually, navigate to your terraform folder:')}`);
            log.message(color.cyan('cd terraform && terraform apply'));
        }
        process.exit(1);
    }
}