# grada addon: ai:bedrock
# Generated by `grada add ai:bedrock`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: no fixed hourly instance cost (usage-billed per 1K input/output
# tokens on InvokeModel calls). Remember to enable model access for your
# chosen model in the AWS Bedrock console first.

# --- Least-Privilege IAM Policy for the ECS Task Role ---
resource "aws_iam_role_policy" "ai_bedrock_access" {
  name = "${local.app_name}-ai-bedrock-access"
  role = aws_iam_role.task_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "bedrock:InvokeModel",
          "bedrock:InvokeModelWithResponseStream"
        ]
        Resource = [
          "arn:aws:bedrock:*::foundation-model/*",
          "arn:aws:bedrock:*:*:inference-profile/*"
        ]
      }
    ]
  })
}

# --- Outputs ---
output "bedrock_model_id" {
  value = "{{BEDROCK_MODEL_ID}}"
}
