# deploy-stack addon: cron
# Generated by `deploy-stack add cron`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: $0/mo fixed baseline (first 14M EventBridge Scheduler
# invocations/mo free); billed only for Fargate seconds while the task runs.

# --- IAM Role assumed by EventBridge Scheduler ---
resource "aws_iam_role" "scheduler_cron_role" {
  name = "${local.app_name}-cron-scheduler-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "scheduler.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
}

# --- Least-privilege permission to launch the scheduled task ---
resource "aws_iam_role_policy" "scheduler_cron_policy" {
  name = "${local.app_name}-cron-scheduler-policy"
  role = aws_iam_role.scheduler_cron_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["ecs:RunTask"]
        Resource = [
          aws_ecs_task_definition.app.arn,
          "${aws_ecs_task_definition.app.arn_without_revision}:*"
        ]
      },
      {
        Effect = "Allow"
        Action = ["iam:PassRole"]
        Resource = [
          aws_iam_role.execution_role.arn,
          aws_iam_role.task_role.arn
        ]
        Condition = {
          StringLike = {
            "iam:PassedToService" = "ecs-tasks.amazonaws.com"
          }
        }
      }
    ]
  })
}

# --- Scheduled task (single schedule per project) ---
resource "aws_scheduler_schedule" "cron" {
  name                         = "${local.app_name}-cron-{{CRON_NAME}}"
  schedule_expression          = "{{SCHEDULE_EXPRESSION}}"
  schedule_expression_timezone = "{{SCHEDULE_TIMEZONE}}"

  flexible_time_window {
    mode = "OFF"
  }

  target {
    arn      = aws_ecs_cluster.main.arn
    role_arn = aws_iam_role.scheduler_cron_role.arn

    ecs_parameters {
      task_definition_arn = aws_ecs_task_definition.app.arn
      launch_type         = "FARGATE"
      task_count          = 1

      network_configuration {
        subnets          = aws_subnet.public[*].id
        security_groups  = [aws_security_group.ecs_tasks.id]
        assign_public_ip = true
      }
    }

    input = jsonencode({
      containerOverrides = [
        {
          name    = "${local.app_name}-container"
          command = ["sh", "-c", {{CRON_COMMAND_JSON}}]
        }
      ]
    })
  }
}

# --- Outputs ---
output "cron_schedule_name" {
  value = aws_scheduler_schedule.cron.name
}

output "cron_schedule_arn" {
  value = aws_scheduler_schedule.cron.arn
}
