# deploy-stack addon: db:dynamodb
# Generated by `deploy-stack add db:dynamodb`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.

# --- Scale-to-Zero DynamoDB Table ---
resource "aws_dynamodb_table" "main" {
  name         = "${local.app_name}-table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "{{PARTITION_KEY}}"

  attribute {
    name = "{{PARTITION_KEY}}"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }
}

# --- VPC Gateway Endpoint (keeps traffic on the AWS network) ---
# The endpoint itself carries no hourly or data-processing charge. The table
# above has no fixed hourly instance cost (usage-billed): table storage
# ($0.25/GB-mo), read/write requests, and PITR continuous backups
# ($0.20/GB-mo once data is written) are billed by usage.
resource "aws_vpc_endpoint" "dynamodb" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.{{REGION}}.dynamodb"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = [aws_route_table.public.id]
}

# --- Least-Privilege IAM Policy for the ECS Task Role ---
resource "aws_iam_role_policy" "dynamodb_access" {
  name = "${local.app_name}-dynamodb-access"
  role = aws_iam_role.task_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem",
          "dynamodb:PutItem",
          "dynamodb:UpdateItem",
          "dynamodb:DeleteItem",
          "dynamodb:Query",
          "dynamodb:Scan",
          "dynamodb:BatchGetItem",
          "dynamodb:BatchWriteItem",
          "dynamodb:DescribeTable"
        ]
        Resource = [
          aws_dynamodb_table.main.arn,
          "${aws_dynamodb_table.main.arn}/index/*"
        ]
      }
    ]
  })
}

# --- Outputs ---
output "dynamodb_table_name" {
  value = aws_dynamodb_table.main.name
}

output "dynamodb_table_arn" {
  value = aws_dynamodb_table.main.arn
}
