# deploy-stack addon: email:ses
# Generated by `deploy-stack add email:ses`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: no fixed hourly instance cost (usage-billed at $0.10 per 1,000
# emails sent). New AWS accounts start in the SES sandbox (verified
# recipients only) — request production access in the SES console to send
# to unverified addresses.

# --- SES Domain Identity ---
# Account-wide singletons per domain/region: scoped to the default
# (production) workspace so PR preview teardowns never delete them.
resource "aws_ses_domain_identity" "ses" {
  count  = terraform.workspace == "default" ? 1 : 0
  domain = "{{SES_DOMAIN}}"
}

resource "aws_ses_domain_dkim" "ses" {
  count  = terraform.workspace == "default" ? 1 : 0
  domain = aws_ses_domain_identity.ses[0].domain
}

resource "aws_ses_domain_mail_from" "ses" {
  count                  = terraform.workspace == "default" ? 1 : 0
  domain                 = aws_ses_domain_identity.ses[0].domain
  mail_from_domain       = "mail.{{SES_DOMAIN}}"
  behavior_on_mx_failure = "UseDefaultValue"
}

{{SES_ROUTE53_RECORDS_BLOCK}}
# --- Least-Privilege IAM Policy for the ECS Task Role ---
resource "aws_iam_role_policy" "ses_send" {
  name = "${local.app_name}-ses-send"
  role = aws_iam_role.task_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["ses:SendEmail", "ses:SendRawEmail"]
        Resource = "*"
        Condition = {
          StringLike = { "ses:FromAddress" = ["*@{{SES_DOMAIN}}", "{{SES_FROM_EMAIL}}"] }
        }
      }
    ]
  })
}

# --- Outputs ---
# In external-DNS mode (no --zone-id), create these records at your DNS
# provider: the verification TXT, the three DKIM CNAMEs
# (`<token>._domainkey.{{SES_DOMAIN}}` -> `<token>.dkim.amazonses.com`),
# the MAIL FROM MX/SPF at `mail.{{SES_DOMAIN}}`, and the DMARC TXT.
output "ses_domain_identity_arn" {
  value = terraform.workspace == "default" ? aws_ses_domain_identity.ses[0].arn : null
}

output "ses_verification_token" {
  value = terraform.workspace == "default" ? aws_ses_domain_identity.ses[0].verification_token : null
}

output "ses_dkim_tokens" {
  value = terraform.workspace == "default" ? aws_ses_domain_dkim.ses[0].dkim_tokens : []
}

output "ses_spf_record" {
  value = "v=spf1 include:amazonses.com ~all"
}

output "ses_dmarc_record" {
  value = "v=DMARC1; p=none;"
}
