# deploy-stack addon: queue:sqs
# Generated by `deploy-stack add queue:sqs`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: no fixed hourly instance cost (usage-billed). The first 1M SQS
# requests/mo are free, then $0.40 per million requests.

# --- Dead-Letter Queue ---
resource "aws_sqs_queue" "dlq" {
  name                      = "${local.app_name}-dlq"
  message_retention_seconds = 1209600
  sqs_managed_sse_enabled   = true
}

# --- Primary Queue ---
resource "aws_sqs_queue" "main" {
  name                      = "${local.app_name}-queue"
  visibility_timeout_seconds = 30
  message_retention_seconds = 345600
  receive_wait_time_seconds = 20
  sqs_managed_sse_enabled   = true
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq.arn
    maxReceiveCount     = 3
  })
}

# --- Least-Privilege IAM Policy for the ECS Task Role ---
resource "aws_iam_role_policy" "queue_sqs_access" {
  name = "${local.app_name}-queue-sqs-access"
  role = aws_iam_role.task_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "sqs:SendMessage",
          "sqs:ReceiveMessage",
          "sqs:DeleteMessage",
          "sqs:ChangeMessageVisibility",
          "sqs:GetQueueAttributes",
          "sqs:GetQueueUrl"
        ]
        Resource = [
          aws_sqs_queue.main.arn,
          aws_sqs_queue.dlq.arn
        ]
      }
    ]
  })
}

{{WORKER_AUTOSCALING_BLOCK}}

# --- Outputs ---
output "sqs_queue_url" {
  value = aws_sqs_queue.main.id
}

output "sqs_queue_arn" {
  value = aws_sqs_queue.main.arn
}

output "sqs_dlq_url" {
  value = aws_sqs_queue.dlq.id
}
